name: clone workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ../pub && git clone git@github.com:wrenlowe/cmsc389T-web-template.git
